#!/usr/bin/env python
import sys, datetime, os

if len(sys.argv) < 3:
  print 'gimme two dates'
  sys.exit(1)

program_name = os.path.basename(sys.argv[0])

dt = lambda x: datetime.datetime.strptime(x, '%Y-%m-%d')
rep = lambda x: x.isoformat().split('T')[0]

try:
  start = dt(sys.argv[1])
  end = dt(sys.argv[2])
except ValueError:
  print 'parse error'
  sys.exit(1)

if end < start:
  print '%s only goes forward' % program_name
  sys.exit(1)

current = start

while current != end:
  print rep(current)
  current = current + datetime.timedelta(days=1)

